### ISSUE TITLE
Facebook App settings

### ISSUE THREAD

**Issue by stefahn** [heiseonline/shariff-backend-php#101]
On my test site Google+ counts and Xing counts work fine, but Facebook counts are not shown out of the box. I'm on my own IP, so that shouldn't be an issue.

I created a Facebook App and added the lines 	
```
"Facebook": {
        "app_id": "1234",
        "secret": "Mein_App-Geheimcode"
 }
```
to my shariff.json. However it still doesn't work. If I try http://mydomain.de/shariff/backend/?url=http%3A%2F%2Fmydomain.de/shariff-test.html I get an error 500.

All I did in the Facebook app was make it public ("Deine App ist gerade live und öffentlich verfügbar."). Do I need to do something else in the app (more permissions) ?

**Comment by liayn** [comment]
Error 500 means server error. Check your webserver logs!

**Comment by stefahn** [comment]
Here's the detailed error I receive:

> <br />
> <b>Fatal error</b>:  Uncaught exception 'Zend\Config\Exception\RuntimeException' with message 'Decoding failed: Syntax error' in /html/shariff/backend/vendor/zendframework/zend-config/src/Reader/Json.php:50
> Stack trace:
> #0 /html/shariff/backend/index.php(21): Zend\Config\Reader\Json-&gt;fromFile('shariff.json')
> #1 /html/shariff/backend/index.php(26): Application::run()
> #2 {main}
>   thrown in <b>/html/shariff/backend/vendor/zendframework/zend-config/src/Reader/Json.php</b> on line <b>50</b><br />

If I remove the Facebook App lines (see first post) from my shariff.json, then the output is `{"googleplus":1,"xing":0}`. So apparently the Facebook counter is missing.

**Comment by liayn** [comment]
You simply have a syntax error in your json file. Open it in an editor that supports syntax highlighting or use some online service to validate it.

**Comment by stefahn** [comment]
True. Forgot one comma before the Facebook lines :/
Now the Facebook counter works.

However it doesn't work with the non-App solution. If only the App solution works, it should be noted in the README I suggest.

**Comment by liayn** [comment]
> However it doesn't work with the non-App solution.
What is the non-app solution and what is the app solution?
No clue what you are referring to

**Comment by stefahn** [comment]
Non-app solution: Just setting `"services": ["Facebook"]`.

App solution: Additionally setting the lines like in my first post + creating a app on Facebook.

**Comment by liayn** [comment]
Well to my understanding the readme clearly states that facebook does not work without appid and stuff.
```
To use the graph api id method to fetch the share count you need to set up an application at facebook.com and pass in the application id and client secret to the options. It seems that the id method returns the most current share count, but it can be only used with an registered application.
```

**Comment by compeak** [comment]
If you do not provide app credentials the shariff backend [falls back to using the FQL API](https://github.com/heiseonline/shariff-backend-php/blob/master/src/Backend/Facebook.php#L29). The last time I checked it still worked but was heavily rate limited ([heise online](http://www.heise.de) would be blocked in about 10 seconds.).

**Comment by compeak** [comment]
Closing due to inactivity. Feel free to reopen.
